[package]
name = "aus-conf-pre"
version = "0.1.0"
entrypoint = "themes/aus-beamer.typ"
authors = ["JL-ghcoder <isjun.liu@gmail.com>"]
license = "MIT"
description = "Slide Theme for Australian Conference Presentations"
homepage = "https://github.com/JL-ghcoder/Typst-Pre-Template"
repository = "https://github.com/JL-ghcoder/Typst-Pre-Template"
keywords = ["touying", "slide", "theme", "austrilia"]
categories = ["presentation"]
exclude = [".github/", "examples/"]

[template]
path = "examples"
entrypoint = "main.typ"
thumbnail = "figures/red.png"